### ISSUE TITLE
do it safe ?

### ISSUE THREAD

**Issue by vahidalvandi** [lathindu1/tutorials#2]
hello . if user change wallet address with chrome inspect it can change receiver ?? 

```
          .request({
                        method: 'eth_sendTransaction',
                        params: [{
                            from: from,
                            to: "**0x6cA0323B6DB3bbC5331614b1E5aFf01C0b1771d6**",
                            value: '0x' + ((amount * 1000000000000000000).toString(16)),
                        }, ],
                    })
```

**Comment by lathindu1** [comment]
HI this is only for instruct the developers. and I have mentioned in article when we are doing this we must have security restrictions. As I doing now. I'm using Livewire to do this job. so It have full security.

**Comment by vahidalvandi** [comment]
please share it ... !!!
thank you
